"""empty message

Revision ID: 24b74d04d717
Revises: 2d3ea304dbda
Create Date: 2023-04-18 07:39:34.471979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b74d04d717'
down_revision = '2d3ea304dbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sender', schema=None) as batch_op:
        batch_op.alter_column('hostname',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('api_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=9),
               existing_nullable=True)
        batch_op.alter_column('api_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=33),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('mailing_list_recipient',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sender', schema=None) as batch_op:
        batch_op.alter_column('mailing_list_recipient',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('api_hash',
               existing_type=sa.String(length=33),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('api_id',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('hostname',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
