"""empty message

Revision ID: 2d3ea304dbda
Revises: 44722d2f8177
Create Date: 2023-04-18 00:16:01.760075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3ea304dbda'
down_revision = '44722d2f8177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme', sa.String(length=64), nullable=True, max_length=6),
    sa.Column('hostname', sa.String(length=64), nullable=True, max_length=15),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True, max_length=15),
    sa.Column('password', sa.String(length=64), nullable=True, max_length=30),
    sa.Column('phone_number', sa.String(length=64), nullable=True, max_length=15),
    sa.Column('api_id', sa.String(length=64), nullable=True, max_length=9),
    sa.Column('api_hash', sa.String(length=64), nullable=True, max_length=33),
    sa.Column('name', sa.String(length=64), nullable=True, max_length=15),
    sa.Column('text', sa.String(length=64), nullable=True, max_length=100),
    sa.Column('mailing_list_recipient', sa.String(length=64), nullable=True, max_length=1000),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_timestamp')

    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    op.drop_table('sender')
    # ### end Alembic commands ###
